### ISSUE TITLE
list contact not sync with config

### ISSUE THREAD

**Issue by ihard** [moira-alert/web2.0#101]
config /var/www/moira/config.json
`
{
	"api_url": "/api",
	"contacts": [
		{"type": "mail", "validation": "^.+@.+\\..+$", "icon": "email"},
		{"type": "telegram", "validation": "", "img": "telegram.ico", "title": "#channel, @username, group", "help": "required to grant @MoiraBot admin privileges for channels, or /start command in groups and personal chats"}
	],
	"paging": {
		"size": 60
	},
	"event_history":{
		"paging": {
			"size": 100
		}
	}
}`
in web interface
![2017-11-08_10-28-53](https://user-images.githubusercontent.com/3078342/32536536-ee004ff4-c46f-11e7-9f83-5aec25ea53e3.png)

**Comment by borovskyav** [comment]
Duplicate with #98
