### ISSUE TITLE
Unexcepted token JSON

### ISSUE THREAD

**Issue by asiekkowa** [moira-alert/web2.0#105]
Hello,

When I run _docker run _moira/web2_ I receive below error.
I have tried to pull the official docker image and build my own from source (to make sure that code in docker is up to date).

![image](https://user-images.githubusercontent.com/22298133/32938814-b7aeb5a2-cb7d-11e7-9d91-d4bbd6137cd1.png)

**Comment by borovskyav** [comment]
Hi! Can u screen last network responses results?

**Comment by asiekkowa** [comment]
Of course! :)
![image](https://user-images.githubusercontent.com/22298133/33007678-1836e198-cdd0-11e7-9e4f-4164b12bcd23.png)
![image](https://user-images.githubusercontent.com/22298133/33007689-295684ec-cdd0-11e7-8fdf-ea2dd040ba98.png)

**Comment by sashasushko** [comment]
At front we expect a JSON file with error message if status is different from 200. I think, it's bug. @borovskyav will tell more.

**Comment by borovskyav** [comment]
Yeah, get settings requests must return status 200, not 304. Seems like you have bug in nginx config. You can see example of config here: https://github.com/moira-alert/web2.0/blob/master/docker/nginx.conf

**Comment by asiekkowa** [comment]
hi @borovskyav 

I decided to try Moira one more time :) But I have the same problem. I have checked the configuration of nginx and it is similar to your example.

Logs:
![image](https://user-images.githubusercontent.com/22298133/51599163-43882380-1eff-11e9-93f9-31fce48f2bb6.png)
![image](https://user-images.githubusercontent.com/22298133/51599278-834f0b00-1eff-11e9-8081-496563054147.png)

Do you have any idea why?

**Comment by asiekkowa** [comment]
hi @borovskyav

I decided to try Moira one more time :) But I have the same problem. I have checked the configuration of nginx and it is similar to your example.

Logs:
![image](https://user-images.githubusercontent.com/22298133/51599551-2869e380-1f00-11e9-8627-df351882b627.png)
![image](https://user-images.githubusercontent.com/22298133/51599584-3fa8d100-1f00-11e9-9509-1d404e403ee3.png)

I use version 2.4.0.0 of Moira Components

Do you have any idea what is wrong?
