### ISSUE TITLE
unnecessary startOffset/endOffset check

### ISSUE THREAD

**Issue by kamaev** [moira-alert/web2.0#117]
https://github.com/moira-alert/web2.0/blob/94932cf899b78730e949b44cf47d83009410c2c8/src/Components/ScheduleEdit/ScheduleEdit.js#L90

This case is already described for backend

**Comment by tihonove** [comment]
> This case is already described for backend
Это хорошо, только это не значит, что на фронте валидация не нужна

**Comment by borovskyav** [comment]
Кажется, что это нормальная ситуация, когда чувак указывает промежуток 23:00 - 8:00

**Comment by tihonove** [comment]
А. Это, типа, работает? Тогда уберу. Надо ещё добавить подсказку, что так можно

**Comment by borovskyav** [comment]
Да, у меня в коде поддерживается это и тестами зафиксировано, про подсказку не знаю, для меня это поведение всегда казалось логичным
