### ISSUE TITLE
Wrong trigger params after creation

### ISSUE THREAD

**Issue by MetikovVadim** [moira-alert/web2.0#119]
After creating trigger with conditions "Watch for value falling" it saves with "Watch for value raising".

**Comment by MetikovVadim** [comment]
Example:
Creating 
![default](https://user-images.githubusercontent.com/6646815/34430652-053b6ed8-ec89-11e7-9803-dba575eba970.png)

Open after creation
![default](https://user-images.githubusercontent.com/6646815/34430660-22e4a0c6-ec89-11e7-8dfa-d74e1863e629.png)

**Comment by sashasushko** [comment]
I can't reproduce.
