### ISSUE TITLE
404 error on notifications and trigger pages

### ISSUE THREAD

**Issue by AlexFinn** [moira-alert/web2.0#124]
Open the notifications page, reload the page.
Nginx log:

`2018/02/06 11:52:21 [error] 3261#3261: *817 open() "/var/www/moira/settings" failed (2: No such file or directory) while sending to client, client: 66.102.9.18, server: moira.company.com, request: "GET /settings HTTP/1.1", host: "moira.company.com"`

trigger page:

`2018/02/06 11:51:23 [error] 3261#3261: *817 open() "/var/www/moira/trigger/05259e55-4d01-4d9c-91dd-639f400afb9b/edit" failed (2: No such file or directory) while sending to client, client: 66.102.9.18, server: moira.company.com, request: "GET /trigger/05259e55-4d01-4d9c-91dd-639f400afb9b/edit HTTP/1.1", host: "moira.company.com"`

Nginx config:

```
server {
  listen 0.0.0.0:80;
  server_name moira.company.com;

  location / {
    root /var/www/moira;
    index index.html;
  }

  location /api/ {
    proxy_pass http://127.0.0.1:8081;
    proxy_set_header X-WebAuth-User $remote_user;
  }
}
```

**Comment by madest92** [comment]
+1

**Comment by zacharya19** [comment]
The issue here is the nginx settings, it should be like that:
```
server {
  listen 0.0.0.0:80;
  server_name moira.company.com;
  root /var/www/moira;

  location / {
    index index.html;
    try_files /$uri /index.html;
  }

  location /api/ {
    proxy_pass http://127.0.0.1:8081;
    proxy_set_header X-WebAuth-User $remote_user;
  }
}
```

**Comment by AlexFinn** [comment]
thanks @zacharya19 :)

**Comment by kamaev** [comment]
Hi! Sorry for late reply, we'll fix our documentation soon!
