### ISSUE TITLE
Values `0` and `-` not sorted

### ISSUE THREAD

**Issue by ivzalser** [moira-alert/web2.0#125]
Sorting by values not work on trigger page when trigger has values `0` and `-` (NODATA) only.
Page sorted by values page looks like this:
![image](https://user-images.githubusercontent.com/19798358/36841488-40aa5bf2-1d6a-11e8-828b-af54f4671ac5.png)

**Comment by borovskyav** [comment]
Ok, i have fixed it, now NODATA metrics is always lower than all of another metrics
