### ISSUE TITLE
limit value of tags to be shown

### ISSUE THREAD

**Issue by kamaev** [moira-alert/web2.0#134]
Web freezes when tries to show all tags if there is too many tags exists.
We probably can show n first tags + "and k-n more.." where k is total count of tags or something else..

**Comment by sashasushko** [comment]
There is a design for this component - https://guides.kontur.ru/controls/token But there isn't implementation. Will try to fix it.

**Comment by sashasushko** [comment]
I will fix this with temp solution. Until Token component will be released.
