### ISSUE TITLE
Subscription is not deleted

### ISSUE THREAD

**Issue by sashasushko** [moira-alert/web2.0#140]
When you delete delivery channel (email for example), subscriptions that linked with this channel will hide, but will not deleted. When you restore this delivery channel, subscription also show again. But with not delivery channel.

**Comment by sashasushko** [comment]
@titusjaka, можешь пофиксить?

**Comment by titusjaka** [comment]
Хорошо :)

**Comment by titusjaka** [comment]
Когда мы удаляем контакт, возможны 3 сценария:

 - нет ни одной подписки с этим контактом → ничего не делаем;
 - есть 1+ подписок только с этим контактом → удаляем такие подписки;
 - есть 1+ подписок с этим и ещё каким-то контактом → удаляем из подписки контакт и обновляем.

**Comment by sashasushko** [comment]
Will fixed on backed.
