### ISSUE TITLE
Add 'maintenance' header when notifier in ERROR state

### ISSUE THREAD

**Issue by titusjaka** [moira-alert/web2.0#154]
Related with https://github.com/moira-alert/moira/pull/90/

## The goal

The goal is to let user know, that Moira isn't working properly.

## How to

There is a new method in API (see PR in moira) `/health/notifier`. It returns JSON: 
```
{
  state: "OK" # "OK|ERROR"
}
```

If notifier is in `ERROR` state, Moira Web should show header on each page.

**Comment by sashasushko** [comment]
В морде есть компонента, которая желтую плашку выводит на ошибки. Можно её использовать.

**Comment by titusjaka** [comment]
@sashasushko, сделаешь? :)

**Comment by borovskyav** [comment]
Предлагаю красную плашку, типа, АААА ВСЕ ПЛОХО. И не убирать ее пока все не прчинится

**Comment by sashasushko** [comment]
Я за вебсокет, есличо. Не игрался ещё с этой штукой

**Comment by borovskyav** [comment]
Не тот это запрос, где вебсокет нужен, предлагаю просто раз в минуту пинговать, либо на загрузку страницы

**Comment by titusjaka** [comment]
Я подумал, что сейчас надо сделать на загрузку страницы. А в релиз 2.4 можно втащить вебсокеты.

**Comment by borovskyav** [comment]
Вебсокеты не нужны. Вообще.

**Comment by sashasushko** [comment]
😭
