### ISSUE TITLE
Another way to ignore states transitions in subscriptions (2.3 release)

### ISSUE THREAD

**Issue by kamaev** [moira-alert/web2.0#160]
Moira Notifier 2.3 will require following keys in subscription data:
- Do not send WARN notifications 
{"ignore_warnings": true} instead of appending "ERROR" into subscription tags
- Send notifications when triggers degraded only
{"ignore_recoverings":true} instead of appending "DEGRADATION" into subscription tags

**Comment by sashasushko** [comment]
Need discussing. I don't understand, what do you want

**Comment by titusjaka** [comment]
Записал гифку с демонстрацией.

![2018-07-20_12-05-56](https://user-images.githubusercontent.com/5277948/42988260-5cf0cffc-8c15-11e8-8db9-c1232232266a.gif)

Суть такая
------

Когда человек нажимает на галочки "Send notifications when triggers degraded only" и "Do not send WARN notifications", внутри состояния в вебе они хранятся как галочки. Но когда они отрпавляются в API, веб отправляет их не галочками, а дополнительными тегами. Мы эту логику на стороне API исправили. Теперь нужно убрать из веба аппенд тегов.

**Comment by sashasushko** [comment]
Okay, let's look together on Monday
