### ISSUE TITLE
Allow user to set the only threshold in simple trigger edit form according to moira-alert/moira#96

### ISSUE THREAD

**Issue by titusjaka** [moira-alert/web2.0#163]
We want to allow user setting only one threshold in simple trigger edit form.

So, we have to refactor our verification checks in WEB UI.

Bond with moira-alert/moira#96

**Comment by sashasushko** [comment]
ToDo:
- add flag `is_rising`
- one of two value can be empty (`null`)

**Comment by titusjaka** [comment]
Короче, мы передумали. Параметр будет называться is_falling и он будет по дефолту в false => триггер Rising.

**Comment by titusjaka** [comment]
Пока притормозим веб. С Аркадием пока подумаем ещё, как лучше сделать бэкенд.

**Comment by titusjaka** [comment]
@sashasushko в целом API готов. В любом случае, меняться в нём уже ничего важного не будет.

Работает так. В модели trigger появляется новое поле `trigger_type`. Это поле может принимать значения: 
- `rising` → Watch for value rising
- `falling` → Watch for value falling
- `expression` → Advanced mode expression

API всегда будет отдавать правильное значение. В зависимости от значения, нужно будет переключать пользователя на нужную вкладку: Simple/Advanced mode и выбирать правильное значение Rising/Falling.

Если по какой-то причине что-то сломается. то придёт либо пустая строка, либо не будет поля совсем (если старое API). 

В API можно передать пустое значение поля `trigger_type`, тогда оно само посчитает правильный вариант. Но логично передавать это поле всегда.

Какие есть валидации в API (их нужно повторить в вебе):

- Если `trigger_type` == `expression`, но поле `expression` не заполнено, то вернётся ошибка
- Если `trigger_type` == `rising`, но warn > error, то вернётся ошибка
- Если `trigger_type` == `falling`, но warn < error, то вернётся ошибка
- Если warn == error, то вернётся ошибка
- Если одно из значений warn/error пустое, и `trigger_type` == `""`, то вернётся ошибка.

**Comment by sashasushko** [comment]
> Если одно из значений warn/error пустое, и trigger_type == "", то вернётся ошибка.
Explain this more concrete

**Comment by titusjaka** [comment]
API может предположить, что это за триггер, только сравнив warn и error. Если warn < error, то триггер rising, если warn > error → falling.

Если мне пришло только одно значение warn/error и не указан тип, то я не могу однозначно решить за пользователя, что он хотел сказать.

Просто всегда отправляй тип триггера, и всё будет ок :)
