### ISSUE TITLE
Make rounding accuracy in event list dynamic

### ISSUE THREAD

**Issue by titusjaka** [moira-alert/web2.0#170]
Moira Web UI rounds numbers in event list to 2nd character after the decimal point: [code](https://github.com/moira-alert/web2.0/blob/7b1df6775f4b71033e1a2f328a9307e3cfe0c939/src/helpers.js#L15).

Sometimes, it leads to odd and unobvious results:

![image](https://user-images.githubusercontent.com/5277948/43636881-c76c2062-972c-11e8-9602-7e3cafda8799.png)

I think, we could round numbers to the first differing characters. In this case it could be 0,001 → 0,000

**Comment by sashasushko** [comment]
But in this case column width will be unexpected. Imagine, if values is like:
```
       0,0000001 → 0,0000000
       0,0000000 → 0,0000001

             0,1 → 0,0
             0,0 → 0,1

0,00000000000001 → 0,00000000000000
0,00000000000000 → 0,00000000000001

            0,01 → 0,00
            0,00 → 0,01
```

**Comment by titusjaka** [comment]
The only thing I can imagine is pop-up with the real not-rounded value. But it sounds odd.

**Comment by sashasushko** [comment]
Need designer help

**Comment by sashasushko** [comment]
It will fixed in next page redesign
