### ISSUE TITLE
Add eslint , prettier and flow checks before committing using husky 

### ISSUE THREAD

**Issue by siddhant1** [moira-alert/web2.0#226]
I think we should add in an eslint check ,prettier formatter and flow checks before committing code.
Should I send in a pull request?

**Comment by sashasushko** [comment]
I don't like check with `--fix` option. Because I think developer must know, what and why changed in his code.

But if prehook only will notice about lint erros, it's good idea. It will clean commit history from "Fix eslint errors" commits :-)
