### ISSUE TITLE
Enhancement :- Move from momentjs to date-fns to improve performance

### ISSUE THREAD

**Issue by siddhant1** [moira-alert/web2.0#227]
This is a very small enhancement in the editor but I we should use date-fns over momentjs because it is super small and imporves performance.

Links :- https://twitter.com/addyosmani/status/1037587112730611714?lang=en

**Comment by sashasushko** [comment]
@siddhant1 why you close this issue? It's good idea

**Comment by siddhant1** [comment]
I closed this issue because it was mentioned that I had to open the issues in the backend repo

**Comment by sashasushko** [comment]
It's true. We place all our issuies in main repo. But if you already open, it's okay. I move issues like this by myself, if we decided to get in work it.

**Comment by sashasushko** [comment]
Move to moira-alert/moira/issues/276
