### ISSUE TITLE
Query regarding work and contributions for GSOC

### ISSUE THREAD

**Issue by nik72619c** [moira-alert/web2.0#242]
Is the project available to work on and contribute for GSOC? Willing to work on it !

**Comment by sashasushko** [comment]
Hi. Yes, of course.

Although official application period for GSoC starts on March 25th, feel free to join our Telegram chat here: https://t.me/moira_alert
 
Also you can try some of our introductory tasks here: https://github.com/orgs/moira-alert/projects/2

**Comment by nik72619c** [comment]
Thanks for the reply !
