### ISSUE TITLE
(Bug?) Drops non-existing tags from query

### ISSUE THREAD

**Issue by androndo** [moira-alert/web2.0#352]
### Case:
1) We have some tags: `one`, `two` and **trigger1** with both.
2) Search by tags 'one', 'two' - OK 
3) Add non-existing tag: `none` to query, then response will not contain these **non-existing** tag, and search result show trigger1.

### Notes:
* Maybe for user will be better return epmty result or some tips about non-existing tags in search query.
* Moira API returns empty result for this case with non-existing triggers, try it for free: 
`<moira-host>/api/trigger/search?tags[0]=Environment%3Dcloud&tags[1]=Application%3DNoSuchApp`. 
* Search in  Moira Web: `<moira-host>/?tags[0]=Environment%3Dcloud&tags[1]=Application%3DNoSuchApp`.

**Comment by sashasushko** [comment]
@androndo sorry for long time response. Please tell me how you add non existent tag to search query? Because our UI has not this option.
![изображение](https://user-images.githubusercontent.com/4469056/129442885-d62583b3-6542-4e9d-bb4e-36a86e94ad6e.png)
