### ISSUE TITLE
Browser back arrow not working

### ISSUE THREAD

**Issue by kissken** [moira-alert/web2.0#381]
# BUG REPORT

You must be on some team.

1. Go into "Notification" page (/settings)
2. Select team (url will be /settings/uid)
3. Click on browser back

## What did you expect to see?

Want to see page user-notification page (/settings)

## What did you see instead?

See page where I was before /settings

### Some helpful notes

[probable place](https://github.com/moira-alert/web2.0/blob/master/src/Containers/SettingsContainer.tsx#L303)
[probable solution](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState)

**Comment by abhijain1705** [comment]
hey can I work on this?

**Comment by kissken** [comment]
@abhijain1705 hello, yes sure :)

**Comment by EduardZaydler** [comment]
fixed
