### ISSUE TITLE
Add sorting on tags page

### ISSUE THREAD

**Issue by ihard** [moira-alert/web2.0#434]
Add sorting of triggers and subscriptions columns on the tags page:
![2023-09-26_15-48-45](https://github.com/moira-alert/web2.0/assets/3078342/f5a6f3fa-ffbd-4d23-b236-aa553243c50a)

similar to the patterns page for metrics and triggers:
![2023-09-26_15-49-09](https://github.com/moira-alert/web2.0/assets/3078342/c1cb4008-248c-4a22-8671-325d5891fd1d)

**Comment by EduardZaydler** [comment]
added here https://github.com/moira-alert/web2.0/pull/491
