### ISSUE TITLE
Sometimes N/A is green, sometimes grey

### ISSUE THREAD

**Issue by beevee** [moira-alert/web2.0#96]
![2017-11-03_17-51-40](https://user-images.githubusercontent.com/1009675/32374484-bb52592a-c0bf-11e7-9b20-804f99f63b86.png)

I think N/A should be grey all the time. It is not normal to have trigger without any metrics.

**Comment by tihonove** [comment]
Fix by @borovskyav https://github.com/moira-alert/moira/commit/90f386a4e5135bd9d55ea8c37da0a4a0421a3661
